# Generated by Django 4.2.24 on 2025-09-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('encouragement', 'Encouragement'), ('reminder', 'Reminder'), ('celebration', 'Celebration'), ('support', 'Support')], max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Patients'), ('low_engagement', 'Low Engagement'), ('high_risk', 'High Risk'), ('progressing', 'Progressing')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('unlock_condition', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SelfCareExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('mindfulness', 'Mindfulness'), ('journaling', 'Journaling'), ('physical', 'Physical Activity'), ('cognitive', 'Cognitive Exercise'), ('social', 'Social Connection')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('instructions', models.TextField()),
                ('benefits', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCarePathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_symptoms', models.JSONField(default=list)),
                ('target_severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(through='selfcare.PathwayExercise', to='selfcare.selfcareexercise')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSelfCareProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfcare.selfcareexercise')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.selfcarepathway')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.motivationalmessage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.AddField(
            model_name='pathwayexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.selfcareexercise'),
        ),
        migrations.AddField(
            model_name='pathwayexercise',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.selfcarepathway'),
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('energy_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('sleep_quality', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('stress_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CoachCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('coach_notes', models.TextField(blank=True)),
                ('patient_feedback', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pathwayexercise',
            unique_together={('pathway', 'exercise')},
        ),
        migrations.CreateModel(
            name='ExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_actual', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfcare.selfcareexercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
            options={
                'unique_together': {('patient', 'exercise', 'completed_at')},
            },
        ),
    ]
