# Generated by Django 4.2.24 on 2025-09-29 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('treatment_goals', models.TextField()),
                ('recommended_interventions', models.TextField()),
                ('medication_notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('assessment', 'Assessment'), ('progress', 'Progress Note'), ('treatment', 'Treatment Note'), ('crisis', 'Crisis Note'), ('discharge', 'Discharge Note')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
                ('gad7_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screening.gad7screening')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
                ('phq9_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screening.phq9screening')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up'), ('teleconsult', 'Teleconsultation'), ('crisis', 'Crisis Intervention')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('fhir_appointment_id', models.CharField(blank=True, max_length=100)),
                ('fhir_patient_id', models.CharField(blank=True, max_length=100)),
                ('fhir_practitioner_id', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('clinician_notes', models.TextField(blank=True)),
                ('patient_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AlertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('action_taken', models.CharField(max_length=100)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.screeningalert')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phq9_score', models.IntegerField(blank=True, null=True)),
                ('phq9_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('gad7_score', models.IntegerField(blank=True, null=True)),
                ('gad7_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('mood_level', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('check_ins_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
            options={
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
            options={
                'unique_together': {('patient', 'clinician')},
            },
        ),
        migrations.CreateModel(
            name='ClinicianDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_patients', models.IntegerField(default=0)),
                ('high_risk_patients', models.IntegerField(default=0)),
                ('new_screenings', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('teleconsults_scheduled', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('critical_risk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinician.clinician')),
            ],
            options={
                'unique_together': {('clinician', 'date')},
            },
        ),
    ]
