# Generated by Django 4.2.24 on 2026-03-28 18:59

from django.db import migrations, models
import django.db.models.deletion


def approve_existing_clinicians(apps, schema_editor):
    Clinician = apps.get_model("clinician", "Clinician")
    Clinician.objects.all().update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='communication_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinician',
            name='max_patients_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clinician',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clinician',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clinician',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClinicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license_certificate', 'License certificate'), ('id_proof', 'ID proof'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='clinician_documents/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinician.clinician')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(approve_existing_clinicians, migrations.RunPython.noop),
    ]
