# Generated by Django 4.2.24 on 2026-03-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0005_consultation_links'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultationcase',
            name='uniq_open_system_case_per_pair',
        ),
        migrations.RenameIndex(
            model_name='consultationcase',
            new_name='clinician_c_assigne_228fe2_idx',
            old_name='clinician_c_assigne_4302db_idx',
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultationthread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='consultationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by_system', True), ('status__in', ['open', 'in_progress', 'awaiting_patient', 'scheduled'])), fields=('patient', 'assigned_clinician', 'status', 'created_by_system'), name='uniq_open_system_case_per_pair'),
        ),
    ]
